name: Wide Log Lines

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Generate wide log lines
        run: |
          b='x'
          for a in $(seq 13); do
            b="$b$b"
            echo "$a:$b"
            echo
          done
